# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.

name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Perform the ruby setup
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      
      -  run: gem install bundler
      - run: bundle install
      
      - name: Perform the rubocop
        run:  rubocop --auto-gen-config
      
      - name: Run the tests
        run: bin/rake
        
      - name: Login to the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build the docker image
        run: docker build -t vinayakb807/samplerubyapp:p2 .
     
      - name: Push the docker image
        run: docker push vinayakb807/samplerubyapp:p2
